In [4]:
import numpy as np
nx=5
x = np.linspace(0, 1, nx)
x

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [6]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
t = np.meshgrid(x, y)

In [7]:
t

[array([[ 0. ,  0.5,  1. ],
        [ 0. ,  0.5,  1. ]]), array([[ 0.,  0.,  0.],
        [ 1.,  1.,  1.]])]

In [8]:
t.shape


AttributeError: 'list' object has no attribute 'shape'

In [9]:
len(t)

2

In [10]:
t[0]

array([[ 0. ,  0.5,  1. ],
       [ 0. ,  0.5,  1. ]])

In [11]:
t[1]

array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.]])

array([ 0. ,  0.5,  1. ])

In [13]:
y

array([ 0.,  1.])

In [14]:
x = np.arange(256)
y = np.arange(256)
xy_mesh = np.meshgrid(x,y)


In [15]:
xy_mesh

[array([[  0,   1,   2, ..., 253, 254, 255],
        [  0,   1,   2, ..., 253, 254, 255],
        [  0,   1,   2, ..., 253, 254, 255],
        ..., 
        [  0,   1,   2, ..., 253, 254, 255],
        [  0,   1,   2, ..., 253, 254, 255],
        [  0,   1,   2, ..., 253, 254, 255]]),
 array([[  0,   0,   0, ...,   0,   0,   0],
        [  1,   1,   1, ...,   1,   1,   1],
        [  2,   2,   2, ...,   2,   2,   2],
        ..., 
        [253, 253, 253, ..., 253, 253, 253],
        [254, 254, 254, ..., 254, 254, 254],
        [255, 255, 255, ..., 255, 255, 255]])]

In [16]:
len(xy_mesh)

2

In [22]:
xy_mesh[0]

array([[  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255],
       ..., 
       [  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255]])

In [23]:
xy_mesh[1]

array([[  0,   0,   0, ...,   0,   0,   0],
       [  1,   1,   1, ...,   1,   1,   1],
       [  2,   2,   2, ...,   2,   2,   2],
       ..., 
       [253, 253, 253, ..., 253, 253, 253],
       [254, 254, 254, ..., 254, 254, 254],
       [255, 255, 255, ..., 255, 255, 255]])